<?php

namespace Sdz\BlogBundle\Repository;

/**
 * ArticleCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
