sdz_blog:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/blog
    requirements:
        _locale: en|fr

sdz_users:
    resource: "@SdzUserBundle/Resources/config/routing.yml"
    prefix:   /users

sdz_users_list:
    path:   /users_list
    defaults:
            _controller: SdzUserBundle:User:index
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

#login:
#    path: /login
#    defaults:
#        _controller: SdzUserBundle:Security:login

#login_check:
#    path: /login_check

#logout:
#    path: /logout

# FOSUserBundle Configuration des routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
